[project]
name = "tea-tool"
version = "0.1.0"
license = {file = "LICENSE"}
readme = "README.md"
description = "Commonly used Python development toolkits in business development."
authors = [
    { name = "Corenca", email = "corenca.wang@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "polars[pyarrow]>=1.44.1",
    "pydantic>=2.13.5",
]

[project.optional-dependencies]
excel = [
    "fastexcel>=0.21.0",
    "xlsxwriter>=3.2.9",
]

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "fastexcel>=0.21.0",
    "ipython>=9.17.1",
    "pytest>=9.1.1",
    "ruff>=0.16.5",
    "xlsxwriter>=3.2.9",
]
